### PR TITLE
nimble/bt5_scanner

### PR DESCRIPTION
**Pull request by rymanluk**
In this pull request you can find  first part of extended advertising feature for controller part and . It contains:
* required PHY changes
* handling non-connectable/connectable/scanable extended advertising packets.
* handling extended connect request

Configuration to run:
* Set Low Power RTC
* Set BLE_LL_CFG_FEAT_LL_EXT_ADV to 1

### CODE REVIEW

**Comment by wes3** [comment]
I am done reviewing the controller changes. Everything other than what I commented on looks good.

**Comment by rymanluk** [comment]
Thanks Will!

**Comment by ccollins476ad** [comment]
I only looked at the changes to the host; they look good to me.  All I saw was a few function renames (inserting "_cmd" into some function names), so please let me know if I missed something.

**Comment by rymanluk** [comment]
Chris, I overwrote previous pull request which contained host part with this one which contains only controller part. I did it because Szymon needs this patches to put his advertiser on top. Once that got merged I will create new pull with host part.

**Comment by wes3** [comment]
Changes look good.

**Pull request merged**
