### PR TITLE
a library to control the HC-SR04 ultrasonic distance sensor

### PR DESCRIPTION
**Pull request by paulfdietrich**
a small library to control an ultrasonic range finder.

### CODE REVIEW

**Comment by mkiiskila** [comment]
Hi Paul, do you feel that the ultrasonic driver should be part of the core OS?
I wonder if the Arduino repository would be a better place to keep this.

Also, setting identities in pkg.yml for this library does not seem right. What's the goal with that setting?

**Comment by ccollins476ad** [comment]
I think this library does need to stay in core because we have a tutorial in the mynewt docs which relies on it (http://mynewt.apache.org/os/tutorials/air_quality_sensor/)

I do agree that the PERIPHERAL feature in libs/HCSR04/pkg.yml seems to serve no purpose, and it should probably be removed.

**Comment by paulfdietrich** [comment]
I will close this as I will put it into a remote repository. I think the tutorial is on an air sensor and not a distance sensor.

**Comment by sterlinghughes** [comment]
Cool, that's great.  Please add a pointer to it when you do so!

**Pull request closed without merging**
