### PR TITLE
Support for multiple filesystems/disk

### PR DESCRIPTION
**Pull request by utzig**
Don't merge - this is WIP and here for initial review.

More on the rationally will be sent to the mailing list later.

### CODE REVIEW

**Comment by utzig** [comment]
Btw, this is good to merge if no issues are found on review.

**Comment by ccollins476ad** [comment]
Hi Fabio,

Sorry it took me so long to get to this.  I am getting some nffs test failures after merging:

```
Testing package fs/nffs/test
Compiling fs/disk/src/disk.c
fs/disk/src/disk.c:21:19: fatal error: fs/fs.h: No such file or directory
 #include <fs/fs.h>
                   ^
```

That fixed easily enough by adding `fs/fs` to `fs/disk`'s dependency list.  However, I am seeing some other failures now:

```
Test failure (fs/nffs/test):
[FAIL] nffs_test_suite/nffs_test_unlink |fs/nffs/test/src/testcases/unlink_test.c:78| failed assertion: rc == 0
[FAIL] nffs_test_suite/nffs_test_unlink |fs/nffs/test/src/nffs_test_utils.c:236| failed assertion: rc == 0
```

I admit I didn't do much investigation.  Would you mind taking a look?

Thanks,
Chris

**Comment by utzig** [comment]
Hi Chris, it was not a dependency problem, `disk` should not depend on `fs/fs`! It was an old `#include` that was left behind. Also the `mkdir/rename` functions had never been updated to support multiple FS, but fixed now!

**Comment by ccollins476ad** [comment]
Thanks, Fabio.  It looks good.

**Pull request merged**
