### PR TITLE
Added the profiles dir. Added Link Lost Service

### PR DESCRIPTION
**Pull request by bgiori**
Added the "net/nimble/profiles" directory to hold adopted profiles and services which do not belong under host. 

Additionally, I added the Link Lost Service (LLS). The LLS specification can be found online [here](https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.link_loss.xml). The full specification can be downloaded [here](https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=303198).

The specification is pretty vague so my implementation may be slightly wrong.

### CODE REVIEW

**Comment by aditihilbert** [comment]
Brian, since it's Link Loss Service, could you please change Lost to Loss in the files? Thanks :)

**Comment by bgiori** [comment]
comments changed

**Comment by bgiori** [comment]
Royally screwed up my fork, going to close and reopen to start fresh.

**Comment by bgiori** [comment]
#83

**Pull request closed without merging**
