### PR TITLE
Fix timtest timer index

### PR DESCRIPTION
**Pull request by louisom**
Change timtest timer index start at 0

### CODE REVIEW

**Comment by utzig** [comment]
LGTM

**Comment by wes3** [comment]
I do not think we want to make this change. The timtest application is a bit of a tricky one as it sort of depends on bsp/mcu for timer support. If the mcu does not have enough timers this application will not work. I think pretty much every mcu will have a few timers so was not terribly worried about this.

Another issue with this change is that TIMER_1 and TIMER_2 syscfg values are set to 1 in syscfg.yml for this app. That is why main.c uses TIMER_1 and TIMER_2.

A better way to change this might be to determine if the timer is actually enabled in main.c and use timers that actually exist without having to really on syscfg.yml (which may not apply to the bsp).

One final note: timtest should not use a timer that the os is using for its timing. So that is another thing to worry about.

**Comment by grapherd** [comment]
@wes3 Or maybe we can move these setting to `pkg.yml`? since I saw that not every bsp have the same setting of timer.

**Comment by aditihilbert** [comment]
@lulouie, this is best handled by the specific app. Coming up with something generic that works for all different bsp/mcu is too tricky. We will be closing this PR.

**Comment by skiiskila** [comment]
@lulouie, could you please close the PR (based on the history and comments).

**Pull request closed without merging**
