### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by gnatyukv**
Can your **BLE** stack be run without **os**? Trerefore, some edits must be done, e.g. all includes like **os_...** may be cut (declaring types and calls). And other control loop may be added, like **while (1) { check states and process events }** Is it possible in principle?

### CODE REVIEW

**Comment by wes3** [comment]
The current BLE stack requires the mynewt OS. We have discussed making this OS agnostic but not removing the OS entirely from the stack. It is certainly possible in principle though.

**Comment by gnatyukv** [comment]
Thank you for that answer. For now, I need to understand, how to accept a **connection request** from the **master** in an **advertising slave**? Your **BLE** stack may help me. So, I want to clarify, in what **chain** (shown below) that is processed? I found **two**:

**/* Chain 1 Begin */**
[ble_phy.c] ble_phy_isr // **interrupt**
**/* Subchain 1 Begin */**
[ble_phy.c] ble_phy_rx_start_isr
[ble_ll.c] ble_ll_rx_start
[ble_ll_adv.c] ble_ll_adv_rx_isr_start
[ble_ll_adv.c] ble_ll_adv_tx_done // **maybe here?**
**/* Subchain 1 End */**
**/* Subchain 2 Begin */**
[ble_phy.c] ble_phy_rx_end_isr
[ble_ll.c] ble_ll_rx_end
[ble_ll_adv.c] ble_ll_adv_rx_isr_end
[ble_ll_adv.c] ble_ll_adv_rx_req // **this function is odd, connection request is ignored, in my opinion, but it mentioned in the function header**
[ble_ll.c] ble_ll_rx_pdu_in // **maybe here?**
**/* Subchain 2 End */**
**/* Chain 1 End */**

**/* Chain 2 Begin */**
[ble_ll.c] ble_ll_task // **infinite loop**
[ble_ll.c] ble_ll_rx_pkt_in
[ble_ll_adv.c] ble_ll_adv_rx_pkt_in
[ble_ll_adv.c] ble_ll_adv_conn_req_rxd
[ble_ll_conn.c] ble_ll_conn_slave_start
[ble_ll_conn.c] ble_ll_conn_created
[ble_ll_conn_hci.c] ble_ll_conn_comp_event_send
[ble_ll_hci.c] ble_ll_hci_event_send
[host_hci.c] ble_hci_transport_ctlr_event_send // **maybe here?**
**/* Chain 2 End */**

**Comment by wes3** [comment]
Vitya:

I am not exactly sure what you are asking. Are you wanting to understand the code flow for an advertiser to accept a connection request? Are you trying to write some code that will process received connection events? Are you trying to use this code as a controller and receive the events over the HCI interface? If you could describe what you are trying to do in more detail I might be able to help more.


FYI, here is slightly more info on the call chains.

The chain on the advertising slave side is this:

ble_phy_isr(): this handles receive start, receive end and transmit end events.

Receive start in advertising state:
ble_phy_rx_start_isr()
ble_ll_rx_start()
ble_ll_adv_rx_isr_start()

The receive isr start function in the advertising state is attempting to determine if the received packet is one that should received or aborted. We abort as early as possible to save unnecessary receive time. If the frame is to be aborted, ble_ll_adv_tx_done() is called. This prods the advertising state machin to emit another advertisement on the next channel or schedule the start of the next advertising event.

Assuming the packet is one we will accept (a CONNECT_REQ in this case):
ble_phy_isr(): process receive end
ble_phy_rx_end_isr()
ble_ll_rx_end()
ble_ll_adv_rx_isr_end()
ble_ll_adv_rx_req()

The advertising receive request function processes scan request and connection request events. Assuming the CONNECT_REQ passes through the appropriate filters, it is handed to the LL task for further processing at task level.
ble_ll_task()
ble_ll_rx_pkt_in()
ble_ll_adv_rx_pkt_in()
ble_ll_adv_conn_req_rxd()
ble_ll_conn_slave_start()

Assuming the packet passes further validations, a connection state machine is started when ble_ll_conn_slave_start() is called. This will then emit a connection complete event using the call chain as you show it.

**Comment by gnatyukv** [comment]
I have a Link Layer (https://github.com/pauloborges/blessed). It can advertise and visible to Android. Then I want to connect to my nRF51 board and transfer data to it in order to upgrade firmware over BLE without using SoftDevice (because it is too large, my employer want that, I go through a test period on programming job). Minimum functionality, no Security, just transferring with respond, Peripheral role. So, I just want to extend that blessed project to be more functional.

**Comment by wes3** [comment]
Ah, I have seen blessed on github. That is cool that you want to extend it. You should be able to use the nimble code to add functionality; let me know if you find any issues with it. We also encourage folks to contribute to the project so if you are so inclined that would be great.

Let us know if you have more questions…

One more thing: it looks like you were not trying to make any changes with your pull request. Given that, we should move this conversation to the dev list and you should close your pull request.

**Comment by sterlinghughes** [comment]
Also, it's worth considering using the mynewt stack and OS.  I understand you want a simpler solution, but if you can #ifdef out the stuff you don't need -- we'll upstream the patch, to allow it to be configurable down to the code size you might need.  I'm not sure how maintained blessed is today.

**Comment by gnatyukv** [comment]
Ok, thanks. I will try to do this work.
About pull request, I don't have a good understanding of github system. I just wanted to ask. I should close this pull request, or any other changes?

**Comment by wes3** [comment]
Yes, you should close this pull request. Not sure what other changes you are referring to.

Furthermore, conversations about the stack and os are better held here: dev@mynewt.incubator.apache.org <mailto:dev@mynewt.incubator.apache.org>

**Pull request closed without merging**
