### PR TITLE
Arduino M0 pro support not included in README.md 

### PR DESCRIPTION
**Pull request by SanjeewaUoM**
Hi,
Mynewt already supports Arduino M0 Pro. But I noticed that it is not mentioned in the README.md

### CODE REVIEW

**Comment by aethaniel** [comment]
@SanjeewaUoM, can you precise in which repo/branch you found Atmel SAMD21 mcu or Arduino Zero BSP, please?

I checked all branches present in this repo without any success... only docs speaks about this board in mynewt.

**Comment by sterlinghughes** [comment]
Hi Thibaut, 

Arduino Zero support is separate from the main mynewt repository, due a  license issue with the Ateml headers.  The BSP can be found here: 

https://github.com/runtimeinc/mynewt_arduino_zero

A tutorial on using Mynewt on the arduino zero is here:

http://mynewt.apache.org/os/tutorials/arduino_zero/

Best,

Sterling

**Comment by aethaniel** [comment]
Hi Sterling,

What is the license issue? AFAIK, it is BSD like and should fit without problem.

Anyway, thanks for the link, i may have missed it in the documentation.

T.

On 18 May 2016 19:30:02 CEST, Sterling Hughes <notifications@github.com> wrote:
>Hi Thibaut, 
>
>Arduino Zero support is separate from the main mynewt repository, due a
> license issue with the Ateml headers.  The BSP can be found here: 
>
>https://github.com/runtimeinc/mynewt_arduino_zero
>
>A tutorial on using Mynewt on the arduino zero is here:
>
>http://mynewt.apache.org/os/tutorials/arduino_zero/
>
>Best,
>
>Sterling 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/incubator-mynewt-core/pull/53#issuecomment-220100143

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by sterlinghughes** [comment]
The license is a pretty standard 3-clause BSD, _except_ they add a 4th clause which states:

 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.

Not really a huge issue for users, because why would you use a MCU header file with anything _but_ the MCU its designed for.  However, it is incompatible with the ASF -- which is against such restrictions.

Runtime has therefore distributed the arduino zero support separately: we've also clarified with Atmel that we are not in anyway violating their license.

**Comment by aethaniel** [comment]
Ok, I will PM you tomorrow about this point.

On 18 May 2016 20:20:21 CEST, Sterling Hughes <notifications@github.com> wrote:
>The license is a pretty standard 3-clause BSD, _except_ they add a 4th
>clause which states:
>
>* 4. This software may only be redistributed and used in connection
>with an
> *    Atmel microcontroller product.
>
>Not really a huge issue for users, because why would you use a MCU
>header file with anything _but_ the MCU its designed for.  However, it
>is incompatible with the ASF -- which is against such restrictions.
>
>Runtime has therefore distributed the arduino zero support separately:
>we've also clarified with Atmel that we are not in anyway violating
>their license.
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/incubator-mynewt-core/pull/53#issuecomment-220114191

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by SanjeewaUoM** [comment]
Hi Thibault,

I didn't checked the branches. I saw some inconsistency between README.md
and this link <https://mynewt.apache.org/os/tutorials/arduino_zero/> (
https://mynewt.apache.org/os/tutorials/arduino_zero/)
In REAM.md, In README.md, under Overview, it says, "It currently supports
the following hardware platforms: Arduino Zero and Zero Pro".
But in the tutorial(the link I provided), it is mentioned that mynewt
supports Arduino M0 Pro.

Hope you got my point.

Hi Stering, thanks for the knowledge you shared.

Regards,
Sanjeewa

**Pull request closed without merging**
