### PR TITLE
nimble/gap: Fix validation of conn parameters

### PR DESCRIPTION
**Pull request by rymanluk**
This fix obvious incorrect check for parameter validation.

### CODE REVIEW

**Comment by sterlinghughes** [comment]
are we ready to merge this?

**Comment by rymanluk** [comment]
I think that one also has some problem with unit test. I scheduled this work for tomorrow. Will put comment when ready.

**Comment by rymanluk** [comment]
ok, had to fixed supervision timeout in unit test so now it is according to spec. 
it's ready to merge

**Comment by rymanluk** [comment]
Added some more unit tests. still ready to merge

**Comment by ccollins476ad** [comment]
Thanks, Łukasz.

**Pull request merged**
